

# Site Settings
title: 						"Context Dallas"
email: 						"info@contextdallas.com"
description: 				"Astro is a content focused responsive theme for the Jekyll blogging platform. Available for purchase at ThemeForest.net."
baseurl: 					""
url: 						"http://www.contextdallas.com"
logourl: 					"/assets/img/bloglogo.jpg"
fa-logo: 					"fa-bookmark-o"
paginate: 					5


# Author Settings
author_name: 				"Walter Higgins"
author_url: 				"http://www.contextdallas.com"
author_bio: 				"Walter Higgins built a career and reputation by breaking the rules. Harvey's shoot-from-the-hip style has made him an effective lawyer and a slick character."
author_email: 				"changarocc@gmail.com"
author_image: 				"/assets/img/authorimage.jpg"


# Social Settings
twitter_url: 				"http://twitter.com"
facebook_url: 				"http://facebook.com"
github_url:  				"http://github.com"
youtube_url:  				"http://youtube.com"
dribbble_url:  				"http://dribbble.com"
googleplus_url: 			"http://google.com/plus"
instagram_url:  			"http://instagram.com"
pinterest_url:  			"http://pinterest.com"
linkedin_url:  				"http://linkedin.com"


# Theme Settings
theme_disqus_shortname: 	"ecko"
theme_google_comments: 		false
theme_analytics_id: 		"UA-28282324-1"
theme_analytics_domain: 	"ecko.me"
theme_reading_time: 		true
theme_autoload_comments: 	false
theme_always_show_nav: 		false


# SASS Settings
# DO NOT MODIFY
sass:
 sass_dir: "assets/css/"
 style: :compressed


# Build Settings
markdown: 					kramdown
permalink: 					pretty

#jekyll-assets plugin
assets:
  # js_compressor:  uglifier

# Prose Settings
prose:
  rooturl: "_posts"
  siteurl: "http://www.contextdallas"
  media: "media
  metadata:
    _posts:
      - name: "date"
        field: 
          element: "hidden"
          value: CURRENT_DATETIME
